/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainBImport } from './routes/_main/b'
import { Route as MainAParamImport } from './routes/_main/a.$param'

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const MainBRoute = MainBImport.update({
  path: '/b',
  getParentRoute: () => MainRoute,
} as any)

const MainAParamRoute = MainAParamImport.update({
  path: '/a/$param',
  getParentRoute: () => MainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_main/b': {
      preLoaderRoute: typeof MainBImport
      parentRoute: typeof MainImport
    }
    '/_main/': {
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/a/$param': {
      preLoaderRoute: typeof MainAParamImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  MainRoute.addChildren([MainBRoute, MainIndexRoute, MainAParamRoute]),
])

/* prettier-ignore-end */
